apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-env
  namespace: minikube
data:
  JICOFO_COMPONENT_SECRET: password
  JICOFO_AUTH_PASSWORD: password
  JVB_AUTH_PASSWORD: password
  JIGASI_XMPP_PASSWORD: password
  JIBRI_RECORDER_PASSWORD: password
  JIBRI_XMPP_PASSWORD: password
  TZ: Asia/Kolkata
  #ETHERPAD_URL_BASE=http://etherpad.minikube.devopsk8s.cf:9001
  ENABLE_AUTH: "1"
  ENABLE_GUESTS: "1"
  AUTH_TYPE: internal
  XMPP_DOMAIN: minikube.devopsk8s.cf
  XMPP_SERVER: prosody
  XMPP_BOSH_URL_BASE: http://prosody:5280
  XMPP_AUTH_DOMAIN: auth.minikube.devopsk8s.cf
  XMPP_MUC_DOMAIN: muc.minikube.devopsk8s.cf
  XMPP_INTERNAL_MUC_DOMAIN: internal-muc.minikube.devopsk8s.cf
  XMPP_GUEST_DOMAIN: guest.minikube.devopsk8s.cf
  JVB_BREWERY_MUC: jvbbrewery
  JVB_AUTH_USER: jvb
  JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
  JVB_PORT: "32220"
  JVB_TCP_HARVESTER_DISABLED: "true"
  JVB_TCP_PORT: "31110"
  JVB_TCP_MAPPED_PORT: "31110"
  JICOFO_AUTH_USER: focus
  ENABLE_RECORDING: "1"
  XMPP_RECORDER_DOMAIN: recorder.minikube.devopsk8s.cf
  JIBRI_RECORDER_USER: recorder
  JIBRI_RECORDING_DIR: /config/recordings
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
  JIBRI_XMPP_USER: jibri
  JIBRI_BREWERY_MUC: jibribrewery
  JIBRI_PENDING_TIMEOUT: "90"
  JIBRI_STRIP_DOMAIN_JID: muc
  JIBRI_LOGS_DIR: /config/logs
  ENABLE_HTTP_REDIRECT: "1"
  RESTART_POLICY: unless-stopped
  DISPLAY: :0
  DOCKER_HOST_ADDRESS: jvb
